version: "3.5"

services:
  postgres:
    container_name: exbidapp_posgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5439:5432"
volumes:
  postgres-db:
    driver: local