name: Elixir CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.15-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Check Code Formatting
        run: mix format --check-formatted

      - name: Compile Code (Check Warnings)
        run: mix compile --warnings-as-errors

      - name: Run Tests
        run: mix test
